spring.application.name=college-placement-system

# ===============================
# Database Configuration
# ===============================
spring.datasource.url=jdbc:postgresql://db.yxvcgzlofwpdavxlpptu.pooler.supabase.com:6543/postgres?sslmode=require
spring.datasource.username=postgres.yxvcgzlofwpdavxlpptu
spring.datasource.password=Rudra@6372992622
spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / Hibernate Configuration
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# Server Configuration
# ===============================
server.port=${PORT:8080}

# ===============================
# Logging
# ===============================
logging.level.org.springframework.web=INFO
logging.level.org.hibernate=ERROR
